# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=1024)),
                ('city_name', models.CharField(max_length=1024)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_parser.City')),
            ],
        ),
    ]
