# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_parser', '0002_airport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airport_code',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='city',
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='altitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='country_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='dst',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
